version: '3'
services:

  manifesto_model:
    build: manifesto_model
    ports:
     - "0.0.0.0:5000:5000"
    environment:
      - PYTHONUNBUFFERED=0 # unbuffered I/O with print etc. to always print to the console
      - HTTP_PORT=5000
      - DB_PATH=/db/active-manifesto.db
#      - PERSISTENCE_HTTP_PORT=8888
    volumes:
      # mount host database inside container
      - ./db/active-manifesto.db:/db/active-manifesto.db
      # mount development files to app
      - ./manifesto_model:/app

  news_crawler:
    build: news_crawler
    ports:
     - "0.0.0.0:5001:5001"
    environment:
      - PYTHONUNBUFFERED=0 # unbuffered I/O with print etc. to always print to the console
      - HTTP_PORT=5001
      - DB_PATH=/db/active-manifesto.db
      - MANIFESTO_MODEL_HTTP_PORT=5000
    volumes:
      # mount host database inside container
      - ./db/active-manifesto.db:/db/active-manifesto.db
      # mount development files to app
      - ./news_crawler:/app

  user_interface:
    build: user_interface
    ports:
     - "0.0.0.0:8080:8080"
    environment:
      - PYTHONUNBUFFERED=0 # unbuffered I/O with print etc. to always print to the console
      - HTTP_PORT=8080
      - MANIFESTO_MODEL_HTTP_PORT=5000
#      - PERSISTENCE_HTTP_PORT=8888
    volumes:
      # mount development files to app
      - ./user_interface:/app
