version: '3'
services:
  manifesto_model:
    build: manifesto_model
    ports:
     - "0.0.0.0:5000:5000"
  news_crawler:
    build: news_crawler
    ports:
     - "0.0.0.0:27017:27017"
  twitter_app:
    build: apps
    ports:
     - "0.0.0.0:5000:5000"
  user_interface:
    build: user_interface
    ports:
     - "0.0.0.0:8080:8080"
