version: '3'
services:
  persistence:
    build: persistence
    ports:
     - "0.0.0.0:8888:8888"
    environment:
      - PYTHONUNBUFFERED=0 # unbuffered I/O with print etc. to always print to the console
      - HTTP_PORT=8888
      - WZB_API_KEY=

  user_interface:
    build: user_interface
    ports:
     - "0.0.0.0:8080:8080"
    environment:
      - PYTHONUNBUFFERED=0 # unbuffered I/O with print etc. to always print to the console
      - HTTP_PORT=8080
      - PERSISTENCE_HTTP_PORT=8888
